# -*- coding: utf-8 -*-
"""Book_Sales_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmNJ9ZP25xzUyEBP9HlCpUqN__0ceExP
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("Books_Data_Clean.csv")

df.head()

df.describe()

df=df[df["Publishing Year"]>1800]

df.describe()

df.isna().sum()

df.dropna(subset="Book Name", inplace=True)

df.duplicated().sum()

df.nunique()

plt.hist(df["Publishing Year"])
plt.xlabel("Publishing Year")
plt.ylabel("Frequency")
plt.title("Distribution of Publishing Year")
plt.show()

df["genre"].value_counts().plot(kind="bar")
plt.xlabel("Genre")
plt.ylabel("No. of books")
plt.title("Distribution of genre")
plt.show()

df.groupby("Author")["Book_average_rating"].mean().sort_values(ascending=False)

sns.boxplot(x="genre",y="Book_ratings_count", data = df)
plt.xlabel("Genre")
plt.ylabel("No. of ratings")
plt.title("Distribution of genre")
plt.show()

plt.scatter(df["sale price"],df["units sold"])
plt.xlabel("sale Price")
plt.ylabel("Units sold")
plt.title("Scatter plot of sale price vs units sold")
plt.show()

language_counts=df["language_code"].value_counts().sort_values(ascending=True)

plt.pie(language_counts,labels=language_counts.index,startangle=90, autopct="%1.1f%%")
plt.title("Distribution of language")
plt.show()

df.groupby("Publisher ")["publisher revenue"].sum().sort_values(ascending=False)

df.groupby("Author_Rating")["Book_ratings_count"].mean().sort_values(ascending=True)

df.groupby("language_code").size().sort_values(ascending=False)

plt.scatter(df["Book_average_rating"],df["Book_ratings_count"])
plt.xlabel("Book Average Rating")
plt.ylabel("Book Ratings Count")
plt.title("Scatter plot of Book Avg Rating and Book Ratings Count")
plt.show()

total_gross_sales_by_author=df.groupby("Author")["gross sales"].sum()

total_gross_sales_by_author.sort_values(ascending=False).head(20).plot(kind="bar")
plt.xlabel("Author")
plt.ylabel("Total Gross Sales")
plt.title("Total Gross Sales By each Author")
plt.show()

sns.boxplot(x="Author_Rating",y="units sold",data=df)
plt.xlabel("Author Rating")
plt.ylabel("Units Sold")
plt.title("Distribution of Author Rating by Units Sold")
plt.show()

df.groupby("Publishing Year")["units sold"].sum().plot(kind="line",marker="o")
plt.xlabel("Publishing Year")
plt.ylabel("Units Sold")
plt.title("Units Sold Over the Years")
plt.show()